name: Verify and build

on:
  workflow_dispatch:

jobs:    
  verify-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'jetbrains'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Unit tests
      run: ./gradlew jacocoTestReport

    - name: Android lint
      id: android-lint
      run: ./gradlew lint

    - name: Ktlint check
      id: ktlint
      run: ./gradlew ktlintMainSourceSetCheck

    - name: Write credentials file
      run: |
        echo ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }} | base64 -d > data/src/main/resources/google_sheets_credentials.json
    
    - name: Build release APK
      run: ./gradlew app:assembleRelease
          
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: APK
        path: app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
                
    - name: Upload unit test report artifact
      uses: actions/upload-artifact@v4
      with:
        name: Unit test report
        path: build/reports/jacoco/jacocoTestReport/html/**
        if-no-files-found: error
        
    - name: Upload failed Android lint check report artifact
      if: ${{ failure() && steps.android-lint.outcome == 'failure' }}
      uses: actions/upload-artifact@v4
      with:
        name: Android lint report
        path: app/build/reports/lint-results-*.*
        if-no-files-found: error
      
    - name: Upload failed Ktlint check report artifact
      if: ${{ failure() && steps.ktlint.outcome == 'failure' }}
      uses: actions/upload-artifact@v4
      with:
        name: Ktlint report
        path: '*/build/reports/ktlint/ktlintMainSourceSetCheck/**'
        if-no-files-found: error
